language: node_js

node_js:
  - 8

install:
  - npm install
  - npm install -g codecov

cache:
  directories:
    - node_modules

script:
  - npm run build
  - npm run server-test
  - npm run report-coverage

env:
  - CI=true